notifications:
  email: false

language: android
jdk: oraclejdk8

env:
  matrix:
    - API=android-27 ABI=armeabi-v7a

#android:
#  components:
#    - platform-tools
#    - tools
#    - build-tools-27.0.2
#    - android-27
#    - sys-img-armeabi-v7a-android-27
#    - extra-android-support
#    - extra-android-m2repository
#  licenses:
#    - 'android-sdk-preview-license-.+'
#    - 'android-sdk-license-.+'
#    - 'google-gdk-license-.+'

before_install:
  - chmod +x gradlew

install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-27.0.2
  - echo y | android update sdk -u -a -t android-27
  - echo y | android update sdk -u -a -t sys-img-armeabi-v7a-android-27
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository

script:
  - ./gradlew clean assemble test

after_success:
  - ./gradlew :library:jacocoTestReport :library:coveralls
