notifications:
  email: false

language: android
jdk: oraclejdk8

env:
  matrix:
    - API=android-27 ABI=armeabi-v7a

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.2
    - android-27
    - sys-img-armeabi-v7a-android-27
    - extra-android-support
    - extra-android-m2repository
  licenses:
#    - 'android-sdk-preview-license-.+'
#    - 'android-sdk-license-.+'
#    - 'google-gdk-license-.+'
    - '.+'

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean assemble test

after_success:
  - ./gradlew :library:jacocoTestReport :library:coveralls
